// <auto-generated />
namespace Hamburger_Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class intToDecimalForPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intToDecimalForPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202105032001353_intToDecimalForPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
